# Generated by Django 5.2.1 on 2025-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_alter_skill_skill_name_alter_skill_skill_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='proposed_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
